#!/bin/sh
# Manual test script: builds the project and runs all unit tests.
set -e

echo "==> Building the project"
go build ./...

echo "==> Running go vet"
go vet ./...

echo "==> Running all unit tests"
go test ./...

echo "==> Running unit tests for modified packages (verbose)"
go test -v ./internal/config/...
go test -v ./internal/database/...
go test -v ./internal/storage/...
go test -v ./internal/systemd/...

echo "==> All tests passed"
